# Issue labels configuration
# Apply with: gh label create <name> --description <desc> --color <color>

- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: enhancement
  color: "a2eeef"
  description: New feature or improvement

- name: triage
  color: "e4e669"
  description: Needs investigation and prioritization

- name: "priority: critical"
  color: "b60205"
  description: Must fix immediately

- name: "priority: high"
  color: "d93f0b"
  description: Fix in current sprint

- name: "priority: medium"
  color: "fbca04"
  description: Fix soon

- name: "priority: low"
  color: "0e8a16"
  description: Nice to have

- name: "area: api"
  color: "1d76db"
  description: API endpoints and routing

- name: "area: ui"
  color: "5319e7"
  description: Web interface

- name: "area: infra"
  color: "006b75"
  description: CI/CD, Docker, deployment

- name: documentation
  color: "0075ca"
  description: Documentation improvements

- name: dependencies
  color: "0366d6"
  description: Dependency updates
